sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f tools/Dockerfile .

script:
  - docker run --rm travis-build tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  - docker run --rm travis-build /bin/bash -c "export NINJA_STATUS='[%f/%t] (%e)' && mkdir build-clang-tidy && cd build-clang-tidy && CXX=clang++-7 CC=clang-7 cmake -GNinja .. && ninja clang-tidy -j $(nproc) -v"
  - docker run --rm travis-build /bin/bash -c "export NINJA_STATUS='[%f/%t] (%e)' && mkdir build-clang-debug && cd build-clang-debug && CXX=clang++-7 CC=clang-7 cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && ninja -j $(nproc) -v && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "export NINJA_STATUS='[%f/%t] (%e)' && mkdir build-clang-release && cd build-clang-release && CXX=clang++-7 CC=clang-7 cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja -j $(nproc) -v && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "export NINJA_STATUS='[%f/%t] (%e)' && mkdir build-gcc-debug && cd build-gcc-debug && CXX=g++-8 CC=gcc-8 cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && ninja -j $(nproc) -v && ctest --output-on-failure && ./benchmark"
  - docker run --rm travis-build /bin/bash -c "export NINJA_STATUS='[%f/%t] (%e)' && mkdir build-gcc-release && cd build-gcc-release && CXX=g++-8 CC=gcc-8 cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja  -j $(nproc) -v && ctest --output-on-failure && ./benchmark"